#!/usr/bin/env python3
"""Intent qualification over a company database.

Usage
-----
  python solution.py --query "Logistic companies in Romania"
  python solution.py --benchmark                 # all 12 benchmark queries
  python solution.py --benchmark --no-escalate   # cheap tier only
  python solution.py --query "..." --explain     # show the plan and stage counts
  python solution.py --warm                      # build the corpus embedding only

Writes JSON and Markdown to results/ when run over the benchmark.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
from pathlib import Path

from iq import config
from iq.cache import DiskCache
from iq.llm import Gemini
from iq.pipeline import QualificationPipeline
from iq.schema import QueryResult

# Company names in this dataset are full of non-ASCII characters (Romanian
# comma-below, Nordic vowels, French accents). The default Windows console
# codepage cannot encode them and raises mid-print, losing the results after
# they have already been paid for.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        try:
            _stream.reconfigure(encoding="utf-8", errors="replace")
        except (ValueError, OSError):
            pass


def _print_spec(result: QueryResult) -> None:
    spec = result.spec
    print("  plan")
    print("    complexity      : {}".format(spec.complexity))
    print("    intent          : {}".format(spec.intent_summary))
    print("    must do         : {}".format(spec.role_statement))
    if spec.countries:
        print("    countries       : {} ({})".format(
            ", ".join(spec.countries[:14]) + ("..." if len(spec.countries) > 14 else ""),
            spec.country_phrase or "resolved",
        ))
    for label, rng in (
        ("employees", spec.employees), ("revenue USD", spec.revenue_usd),
        ("founded", spec.founded_year),
    ):
        if rng.is_set():
            print("    {:<16}: {}".format(label, rng.describe()))
    if spec.is_public is not None:
        print("    {:<16}: {}".format("is_public", spec.is_public))
    if spec.naics_prefixes:
        print("    naics prefixes  : {}".format(", ".join(spec.naics_prefixes)))
    for c in spec.criteria:
        print("    criterion       : {} ({}, w={:.2f})".format(
            c.name, "must" if c.must_have else "nice", c.weight))
    for d in spec.disqualifiers:
        print("    not fooled by   : {}".format(d))


def print_result(result: QueryResult, limit: int = 20, explain: bool = False) -> None:
    print("\n" + "=" * 100)
    print("QUERY: {}".format(result.query))
    print("=" * 100)
    if explain:
        _print_spec(result)
    counts, timings = result.stage_counts, result.timings
    print(
        "  funnel: {} in database -> {} pass hard filters -> {} shortlisted -> "
        "{} escalated -> {} returned ({} qualified)".format(
            counts.get("database", 0), counts.get("after_filter", 0),
            counts.get("shortlist", 0), counts.get("escalated", 0),
            counts.get("returned", 0), counts.get("qualified", 0),
        )
    )
    if counts.get("filter_relaxed"):
        print("  note: numeric filters were relaxed -- they had emptied the result set")
    print("  {:.1f}s total | {} llm calls | {} cache hits | ${:.5f}".format(
        timings.get("total", 0.0), result.usage.calls, result.usage.cached_calls,
        result.usage.cost_usd,
    ))
    if not result.companies:
        print("\n  no companies qualified.")
        return
    print()
    print("  {:<3} {:<36} {:<20} {:>6} {:<10} {}".format(
        "#", "company", "location", "score", "verdict", "why"))
    print("  " + "-" * 128)
    for i, rc in enumerate(result.companies[:limit], start=1):
        flag = "^" if rc.qualification.escalated else " "
        print("  {:<3} {:<36} {:<20} {:>6.3f} {:<10}{} {}".format(
            i, rc.company.name[:36], rc.company.location()[:20], rc.score,
            rc.qualification.verdict.value, flag, rc.qualification.reason[:74],
        ))
    if len(result.companies) > limit:
        print("  ... and {} more".format(len(result.companies) - limit))


def _markdown(results: list[QueryResult], limit: int = 15) -> str:
    lines = ["# Qualified companies by query", ""]
    lines.append("Generated by `solution.py --benchmark`. `^` marks a company whose")
    lines.append("verdict came from the escalation tier rather than the cheap tier.")
    lines.append("")
    for r in results:
        lines.append("## {}".format(r.query))
        lines.append("")
        c = r.stage_counts
        lines.append(
            "*{} complexity | {} of {} passed hard filters | {} shortlisted | "
            "{} escalated | {} returned | {:.1f}s | ${:.5f}*".format(
                r.spec.complexity, c.get("after_filter", 0), c.get("database", 0),
                c.get("shortlist", 0), c.get("escalated", 0), c.get("returned", 0),
                r.timings.get("total", 0.0), r.usage.cost_usd,
            )
        )
        lines.append("")
        if not r.companies:
            lines.append("No companies qualified.")
            lines.append("")
            continue
        lines.append("| # | Company | Location | Score | Verdict | Rationale |")
        lines.append("|---:|---|---|---:|---|---|")
        for i, rc in enumerate(r.companies[:limit], start=1):
            reason = rc.qualification.reason.replace("|", "/")
            mark = "^" if rc.qualification.escalated else ""
            lines.append("| {} | {} | {} | {:.3f} | {}{} | {} |".format(
                i, rc.company.name, rc.company.location(), rc.score,
                rc.qualification.verdict.value, mark, reason,
            ))
        lines.append("")
    return "\n".join(lines)


async def run(args: argparse.Namespace) -> int:
    cfg = config.PipelineConfig()
    if args.no_escalate:
        cfg.escalate_enabled = False
    if args.no_cache:
        cfg.use_cache = False
    if args.shortlist:
        cfg.shortlist_by_complexity = {
            k: args.shortlist for k in cfg.shortlist_by_complexity
        }

    pipeline = QualificationPipeline.from_file(args.data, cfg)
    cache = DiskCache(config.CACHE_DIR / "iq.sqlite", cfg.use_cache)
    pipeline.cache = cache

    async with Gemini(cache, cfg) as client:
        if args.warm:
            t0 = time.perf_counter()
            await pipeline.warm(client, rebuild=args.rebuild)
            assert pipeline.index is not None
            print("corpus embedded: {} x {} in {:.1f}s".format(
                pipeline.index.matrix.shape[0], pipeline.index.matrix.shape[1],
                time.perf_counter() - t0,
            ))
            return 0

        if args.benchmark:
            from evaluation.queries import QUERIES

            queries = [q.text for q in QUERIES]
        elif args.query:
            queries = [args.query]
        else:
            print("nothing to do: pass --query, --benchmark or --warm", file=sys.stderr)
            return 2

        t0 = time.perf_counter()
        await pipeline.warm(client)
        warm_s = time.perf_counter() - t0

        t0 = time.perf_counter()
        results = (
            await pipeline.run_many(client, queries, args.parallel)
            if len(queries) > 1
            else [await pipeline.run(client, queries[0])]
        )
        wall = time.perf_counter() - t0

        for r in results:
            print_result(r, args.limit, args.explain or len(queries) == 1)

        total_cost = sum(r.usage.cost_usd for r in results)
        total_calls = sum(r.usage.calls for r in results)
        print("\n" + "=" * 100)
        print("{} queries | {:.1f}s wall ({:.1f}s/query) | {} llm calls | ${:.5f} "
              "| corpus warm {:.1f}s".format(
                  len(results), wall, wall / max(1, len(results)), total_calls,
                  total_cost, warm_s))
        print("cache: {}".format(json.dumps(cache.stats())))

        if args.benchmark or args.save:
            config.RESULTS_DIR.mkdir(parents=True, exist_ok=True)
            payload = {
                "config": {
                    "qualifier": config.QUALIFIER.primary,
                    "escalation": config.ESCALATION.primary if cfg.escalate_enabled else None,
                    "planner": config.PLANNER.primary,
                    "shortlist": cfg.shortlist_by_complexity,
                },
                "totals": {
                    "queries": len(results), "wall_seconds": round(wall, 2),
                    "llm_calls": total_calls, "cost_usd": round(total_cost, 6),
                },
                "results": [
                    {
                        "query": r.query,
                        "error": r.error,
                        "complexity": r.spec.complexity,
                        "role_statement": r.spec.role_statement,
                        "ideal_profile": r.spec.ideal_profile,
                        "countries": r.spec.countries,
                        "stage_counts": r.stage_counts,
                        "timings": {k: round(v, 3) for k, v in r.timings.items()},
                        "usage": r.usage.to_dict(),
                        "companies": [rc.to_dict() for rc in r.companies],
                    }
                    for r in results
                ],
            }
            out_json = config.RESULTS_DIR / "results.json"
            out_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            out_md = config.RESULTS_DIR / "results.md"
            out_md.write_text(_markdown(results), encoding="utf-8")
            print("wrote {} and {}".format(out_json, out_md))
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--query", "-q", help="a single natural-language query")
    p.add_argument("--benchmark", action="store_true", help="run all 12 benchmark queries")
    p.add_argument("--data", default=str(config.DATA_DIR / "companies.jsonl"))
    p.add_argument("--limit", type=int, default=20, help="rows to print per query")
    p.add_argument("--parallel", type=int, default=2, help="queries in flight at once")
    p.add_argument("--shortlist", type=int, help="override the shortlist size for all complexities")
    p.add_argument("--explain", action="store_true", help="print the query plan")
    p.add_argument("--no-escalate", action="store_true", help="disable the escalation tier")
    p.add_argument("--no-cache", action="store_true", help="bypass the response cache")
    p.add_argument("--warm", action="store_true", help="build the corpus embedding and exit")
    p.add_argument("--rebuild", action="store_true", help="force re-embedding the corpus")
    p.add_argument("--save", action="store_true", help="write results/ even for a single query")
    args = p.parse_args()
    try:
        return asyncio.run(run(args))
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
